name: pr-labeler

on:
  pull_request:
    branches:
      - main
    types: [open, synchronize, reopened, ready_for_review]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: MokkeMeguru/pr-labeler@fd1b0670122188bb80d48258602d4c8b499aacb6
        with:
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          exclude_files: "(?<extention>.txt|.gen.go|.md|go.sum|go.mod)$"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
